image: docker:git
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
services:
  - docker:dind
before_script:
  - apk add --update bash coreutils tar
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
kinetic:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=kinetic
melodic:
  script: .industrial_ci/gitlab.sh ROS_DISTRO=melodic